version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.73
    steps:
      - run:
          command: |
            sudo pip3 install pipenv
            pipenv install
      - run:
          command: |
            pip3 install -r requirements.txt
      - run:
          command: |
            python3 build/genoken/modules_test.py