version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: python-requirements-V2-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - save_cache:
          paths:
            - ".venv"
            - "~/.cache/pip"
            - "/usr/local/lib/python3.7/site-packages"
          key: python-requirements-V2-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . venv/bin/activate
            python build/genoken/modules_test.py
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - run:
          command: |
            python build/genoken/modules_test.py


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build