version: 2.1

jobs:
  build-install-packages:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: python-requirements-V3-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            sudo pip install -r requirements.txt
      - save_cache:
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.7/site-packages"
          key: python-requirements-V3-{{ checksum "requirements.txt" }}
  test-simple-modules:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
            key: python-requirements-V3-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run python build/genoken/modules_test.py
  build-genoken:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: venv-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip3 install virtualenv
            virtualenv -p python3 venv
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - venv
          key: venv-requirements-V1-{{ checksum "requirements.txt" }}
  test-genoken:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: venv-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          command: |
            source venv/bin/activate
            python build/genoken/modules_test.py
      - run:
          command: |
            source venv/bin/activate
            python build/genoken/fasta_util_test.py

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
#      - build-install-packages
      - build-genoken
#      - test-simple-modules:
#          requires:
#            - build-install-packages
      - test-genoken:
          requires:
            - build-genoken
#      - hold:
#          type: approval
#          requires:
#            - build-install-packages
#            - test-simple-modules
#            - build-with-venv
#            - test-with-venv