version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V2-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - save_cache:
          paths:
            - "venv"
          key: python-requirements-V2-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . venv/bin/activate
            python3 build/genoken/modules_test.py


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build