version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: python-requirements-V3-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            sudo pip install -r requirements.txt
      - save_cache:
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.7/site-packages"
          key: python-requirements-V3-{{ checksum "requirements.txt" }}
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
            key: python-requirements-V3-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run python build/genoken/modules_test.py
  build-with-venv:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: python-requirements-V3-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          paths:
            - venv/
          key: python-requirements-V3-{{ checksum "requirements.txt" }}
  test-with-venv:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: python-requirements-V3-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            python3 build/genoken/modules_test.py


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-with-venv:
          requires:
            - build
            - test
      - test-with-venv:
          requires:
            - build
            - test
            - build-with-venv
      - hold:
          type: approval
          requires:
            - build
            - test
            - build-with-venv
            - test-with-venv