version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - save_cache:
          paths:
            - "venv"
          key: python-requirements-V1-{{ checksum "requirements.txt" }}


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build